## Creación de la base de datos

In [4]:
import sqlite3

def create_users_register_table():
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS users_register (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT,
            email TEXT,
            run TEXT,
            curso TEXT,
            electivo_1 TEXT,
            electivo_2 TEXT,
            electivo_3 TEXT,
            electivo_fg TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.commit()
    conn.close()

def create_email_table():
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS emails (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT,
            run TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.commit()
    conn.close()
    
def create_electives_table():
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS electives_control (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            electivos_disponibles TEXT
        )
        """
    )
    conn.commit()
    conn.close()

def create_electives_list_2024_3_medio_table():
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS listado_electivos_2024_3_medio (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run TEXT,
            curso TEXT,
            electivo_1 TEXT,
            electivo_2 TEXT,
            electivo_3 TEXT
        )
        """
    )
    conn.commit()
    conn.close()

In [5]:
create_electives_list_2024_3_medio_table()

In [103]:
create_email_table()

## Leer el contenido de una tabla

In [6]:
import pandas as pd
import sqlite3  # Asegúrate de importar sqlite3

def read_table(table_name, db='form_app.db'):
    conn = sqlite3.connect(db)
    cursor = conn.cursor()

    try:
        cursor.execute(f"PRAGMA table_info({table_name});")
        att_table = [info[1] for info in cursor.fetchall()]

        cursor.execute(f"SELECT * FROM {table_name};")
        table_content = cursor.fetchall()

        df_table = pd.DataFrame(table_content, columns=att_table)
    except Exception as e:
        print(f"Error: {e}")
        df_table = pd.DataFrame()  # Devolver un DataFrame vacío en caso de error
    finally:
        conn.close()

    return df_table

In [34]:
table_name = "listado_electivos_2024_3_medio"
db = "form_app.db"

read_table(table_name, db)

,id,run,curso,electivo_1,electivo_2,electivo_3
0,1,224332564,3º Medio B,Física,Ciencias del Ejercicio Físico y Deportivo,Interpretación Musical
1,2,22464776K,3º Medio A,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
2,3,224793626,3º Medio B,Diseño y arquitectura,Biología celular y molecular,Interpretación Musical
3,4,224793839,3º Medio B,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
4,5,225014434,3º Medio A,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
...,...,...,...,...,...,...
69,70,226483306,3º Medio B,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
70,71,226600493,3º Medio A,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
71,72,226821848,3º Medio B,Diseño y arquitectura,Biología celular y molecular,Seminario de filosofía
72,73,227016558,3º Medio B,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
73,74,227150645,3º Medio B,Física,Ciencias del Ejercicio Físico y Deportivo,Seminario de filosofía

## Eliminar los datos de la tabla

In [8]:
import sqlite3

table_name = "users_register"
db = "form_app.db"

def delete_all_data_from_table(table_name, db):
    conn = sqlite3.connect(db)
    cursor = conn.cursor()

    try:
        cursor.execute(f"DELETE FROM {table_name};")  # Elimina todos los datos
        conn.commit()  # Asegúrate de guardar los cambios
        print(f"Todos los datos de la tabla '{table_name}' han sido eliminados.")
    except Exception as e:
        print(f"Error al eliminar datos: {e}")
    finally:
        conn.close()  # Asegúrate de cerrar la conexión

def drop_table(table_name, db):
    conn = sqlite3.connect(db)
    cursor = conn.cursor()

    try:
        cursor.execute(f"DROP TABLE {table_name};")  # Elimina la tabla
        conn.commit()  # Asegúrate de guardar los cambios
        print(f"La tabla '{table_name}' ha sido eliminada.")
    except Exception as e:
        print(f"Error al eliminar la tabla: {e}")
    finally:
        conn.close()  # Asegúrate de cerrar la conexión

In [7]:
# Llamar a la función
delete_all_data_from_table('emails', 'form_app.db')

Todos los datos de la tabla 'emails' han sido eliminados.

In [8]:
table_name = "emails"

read_table(table_name, db)

Empty DataFrame
Columns: [id, email, run, created_at]
Index: []

In [102]:
table_name = "emails"

# read_table(table_name, db)
# delete_all_data_from_table(table_name, db)
# drop_table(table_name, db)

La tabla 'emails' ha sido eliminada.

## Insertar emails a la tabla email

In [9]:
def insert_email(run, email):
    conn = sqlite3.connect('form_app.db')
    cursor = conn.cursor()
    cursor.execute(
        """
        INSERT INTO emails (run, email)
        VALUES (?, ?)
        """,
        (run, email),
    )
    conn.commit()
    conn.close()

In [14]:
df_users_II_G = pd.read_excel("correos.xlsx", sheet_name=0)
df_users_II_G.columns

# insert_email("micorreo@gmail.com")

Index(['Nº de lista', 'RUN', 'Género', 'Apellido paterno', 'Apellido materno',
       'Nombres', 'Email', 'Fono estudiante', 'Dirección del estudiante',
       'Nombre contacto emergencia', 'Fono emergencia'],
      dtype='object')

In [19]:
df_users_II_B = pd.read_excel("correos.xlsx", sheet_name=1)
df_users_II_B

,Nº de lista,RUN,Género,Apellido paterno,Apellido materno,Nombres,Email,Fono estudiante,Dirección del estudiante,Nombre contacto emergencia,Fono emergencia
0,1,227986972,M,Acevedo,Guzmán,Krishna Anaís Magdalena,Krishna.acevedo@estudiantes.colegiotgs.cl,NaN,Carlos rojas Villalon 580 villa los artesanos,NaN,NaN
1,2,228985147,F,Acevedo,Osorio,Sebastián Ignacio,Sebastian.acevedo@estudiantes.colegiotgs.cl,NaN,Luis Lopez Orellana 2628 villa jorge muoz,NaN,NaN
2,3,226415637,F,Aguilar,Riquelme,Araksy Francoise,Araksy.aguilar@estudiantes.colegiotgs.cl,NaN,Cecilia 299 villa las palmeras,NaN,NaN
3,4,223846807,F,Albornoz,Hermosilla,Rocio Ignacia,Rocio.albornoz@estudiantes.colegiotgs.cl,NaN,Condominio san luis parcela 57 calera de tango,NaN,NaN
4,5,228359157,M,Arce,Nahuelpi,Emily Shamira,Emily.arce@estudiantes.colegiotgs.cl,NaN,Juanita coria duran 365,NaN,NaN
5,6,23052582K,F,Arenas,Salas,Martín Renato,Martin.arenas@estudiantes.colegiotgs.cl,NaN,Calle los pajarito s/n altura 1200 condominio ...,NaN,NaN
6,7,229045555,M,Burgos,Jerez,Sofía Antonia,Sofia.burgos@estudiantes.colegiotgs.cl,NaN,Camino el papagayo sector el mirador sin numero,NaN,NaN
7,8,228317888,M,Cabello,Verdejo,Sebastián Benjamín,Sebastian.cabello@estudiantes.colegiotgs.cl,NaN,Camino la palma parcela 11 lote 33,NaN,NaN
8,9,227228512,M,Cabrera,Cabrera,Camilo Javier,Camilo.cabrera@estudiantes.colegiotgs.cl,NaN,Av troncal 700 depto 15 las praderas 2,NaN,NaN
9,10,227892277,M,Cabrera,Urbina,Carlos Vicente,Carlos.cabrera@estudiantes.colegiotgs.cl,63387728.0,"Las Vertientes, 2 casa 180, Peaflor",NaN,NaN
10,11,227908521,F,Cardona,Montoya,Emanuel,Emanuel.cardona@estudiantes.colegiotgs.cl,NaN,Villa Cantaros De Agua Pje 6 N 3313,NaN,NaN
11,12,22885803K,F,Cerda,Carrillo,Aylin Constanza,Aylin.cerda@estudiantes.colegiotgs.cl,NaN,El olivetto 0160,NaN,NaN
12,13,227080205,M,De Pablo,Aliaga,María De Los Angeles,Maria.depablo@estudiantes.colegiotgs.cl,NaN,Av vicua mackena 350,NaN,NaN
13,14,228391484,M,Díaz,Villegas,Martín Alejandro,Martin.diaz@estudiantes.colegiotgs.cl,NaN,"Nueva Peaflor pasaje 11 casa 423, Peaflor",NaN,NaN
14,15,227110988,M,Faúndez,Herríquez,Javier Alejandro,Javier.faundez@estudiantes.colegiotgs.cl,NaN,Cordillera de la sal 197 villa la arboleda,NaN,NaN
15,16,229071653,F,Gijón,Padilla,Matías Alejandro,Matias.gijon@estudiantes.colegiotgs.cl,NaN,Margot dualde soto mayo 010 manzana 20 villa m...,NaN,NaN
16,17,228986003,F,Gómez,Zúñiga,Josefina Antonia,Josefina.gomez@estudiantes.colegiotgs.cl,NaN,Villa cantaros de agua pasaje 5 numero 3282,NaN,NaN
17,18,22949127K,F,Gormaz,Velasco,Benjamín Felipe,Benjamin.gormaz@estudiantes.colegiotgs.cl,NaN,Francisco hidalgo 57,NaN,NaN
18,19,229044788,F,Hernández,Castro,Paulina Alejandra,Paulina.hernandez@estudiantes.colegiotgs.cl,NaN,Pje Socio Jonathan Bravo 3662 villa puertas de...,NaN,NaN
19,20,22761045K,M,Huerta,Bravo,Trinidad Antonia,Trinidad.huerta@estudiantes.colegiotgs.cl,NaN,Armijo 206 Casa A Cond. Sta Isabel,NaN,NaN
20,21,229412841,F,Humeres,Ulloa,Javiera Alejandra,Javiera.humeres@estudiantes.colegiotgs.cl,NaN,Pje cecilia 299 villa las palmeras,NaN,NaN
21,22,227717173,F,Jaña,Sepulveda,Matilda Ornella,Matilda.jana@estudiantes.colegiotgs.cl,NaN,Camino Interior (loreto) S/n Condominio La Caa...,NaN,NaN
22,23,229307142,F,Jones,Valdebenito,Florencia Pascal,Florencia.jones@estudiantes.colegiotgs.cl,NaN,Presvitero feliz saragoza 2163 malloco,NaN,NaN
23,24,227929723,M,Labraña,Maulén,Benjamín Fernando,Benjamin.labrana@estudiantes.colegiotgs.cl,NaN,Pje Peumo 2611,NaN,NaN
24,25,228588113,F,Lacroix,Lacroix,Gaston Alfonso,Gaston.lacroix@estudiantes.colegiotgs.cl,NaN,Jose quintero 716,NaN,NaN
25,26,22976134K,M,Lagos,Vera,Florencia,Florencia.lagos@estudiantes.colegiotgs.cl,NaN,Pasaje Jerusalem 1707,NaN,NaN
26,27,227098740,F,Lazo,Briones,Álvaro Adolfo,Alvaro.lazo@estudiantes.colegiotgs.cl,NaN,Villa cantaros de agua pasaje 7 casa 3300,NaN,NaN
27,28,22590829K,F,Miño,Yañez,Mariaignacia,Mariaignacia.mino@estudiantes.colegiotgs.cl,NaN,Pasaje lago chungar 1241 B villa santa blanca 3,NaN,NaN
28,29,224479077,F,Montes,Catalán,Agustina Ignacia,Agustina.montes@estudiantes.colegiotgs.cl,NaN,"Las Aguilas 3007, Peaflor",NaN,NaN
29,30,228155071,M,Moreno,Parada,Antonella Alexandra,Antonella.moreno@estudiantes.colegiotgs.cl,NaN,"CAmino El Huanaco, 6000 Peaflor.",NaN,NaN
30,31,229443593,F,Navarro,Navia,María Ignacia,Maria.navarro@estudiantes.colegiotgs.cl,NaN,"Pasaje los Hilanderos 1383, Valle el Encanto",NaN,NaN
31,32,227900296,F,Puente,Schnettler,Benjamin Ignacio,Benjamin.puente@estudiantes.colegiotgs.cl,NaN,Parroco agustin lobos sur 608,NaN,NaN
32,33,22824192K,F,Ramenzoni,Armijo,Agustina Paz,Agustina.ramenzoni@estudiantes.colegiotgs.cl,931999539.0,Moises Chacon 71,Nancy Armijo,931999539.0
33,34,225034214,F,Roa,Castro,Jorge Andrés,Jorge.roa@estudiantes.colegiotgs.cl,NaN,"Granate 572 Villa el cuarso, el Monte",NaN,NaN
34,35,228010758,M,Rubilar,Catalán,Lindsay Andrea,Lindsay.rubilar@estudiantes.colegiotgs.cl,NaN,Pje 3 Casa 329 villa la palma,NaN,NaN
35,36,22791419K,M,San Martín,Carrasco,Sergio Alejandro,Sergio.sanmartin@estudiantes.colegiotgs.cl,NaN,Luis lopez orellana 2641 villa jorge muoz,NaN,NaN
36,37,227884770,F,Sepúlveda,Gallo,Gustavo Andrés,Gustavo.sepulveda@estudiantes.colegiotgs.cl,NaN,Villarica 2269,NaN,NaN
37,38,228032778,F,Trujillo,Jara,Aranza Simone,Aranza.trujillo@estudiantes.colegiotgs.cl,NaN,Calle San Guillermo Parcela 114 Condominio Don...,NaN,NaN
38,39,228144061,M,Ubeda,Ocares,Isidora Ignacia,Isidora.ubeda@estudiantes.colegiotgs.cl,NaN,Paula Verdugo 322 villa los heroes,NaN,NaN
39,40,230350590,F,González,Soto,Kristen Almendra,kristen.gonzalez@estudiantes.colegiotgs.cl,949336228.0,los ulmos 2896,NaN,NaN

In [15]:
for run, email in zip(df_users_II_G['RUN'], df_users_II_G['Email']):
    insert_email(run, email)

In [68]:
read_table('emails')

,id,email,run,created_at
0,34,Bastian.armijo@estudiantes.colegiotgs.cl,228756466,2024-09-11 19:19:10
1,35,bastian.barros@estudiantes.colegiotgs.cl,229306154,2024-09-11 19:19:10
2,36,Viviana.canete@estudiantes.colegiotgs.cl,228141984,2024-09-11 19:19:10
3,37,Vicente.celis@estudiantes.colegiotgs.cl,22739630K,2024-09-11 19:19:10
4,38,Contreras.agustin@estudiantes.colegiotgs.cl,229240994,2024-09-11 19:19:10
5,39,Franco.delafuente@estudiantes.colegiotgs.cl,228576964,2024-09-11 19:19:10
6,40,Maximiliano.delapuente@estudiantes.colegiotgs.cl,229798081,2024-09-11 19:19:10
7,41,Martina.donoso@estudiantes.colegiotgs.cl,227786353,2024-09-11 19:19:10
8,42,Bastian.escobar@estudiantes.colegiotgs.cl,228311898,2024-09-11 19:19:10
9,43,Gaspar.fuentes@estudiantes.colegiotgs.cl,228746746,2024-09-11 19:19:10
10,44,Leila.garrido@estudiantes.colegiotgs.cl,229535528,2024-09-11 19:19:10
11,45,Claudio.gonzalez@estudiantes.colegiotgs.cl,228757454,2024-09-11 19:19:10
12,46,Francisca.huerta@estudiantes.colegiotgs.cl,227610700,2024-09-11 19:19:10
13,47,Samuel.jara@estudiantes.colegiotgs.cl,227310596,2024-09-11 19:19:10
14,48,Santiago.letelier@estudiantes.colegiotgs.cl,229005952,2024-09-11 19:19:10
15,49,Vicente.letelier@estudiantes.colegiotgs.cl,229006231,2024-09-11 19:19:10
16,50,Antonia.liberona@estudiantes.colegiotgs.cl,227655011,2024-09-11 19:19:10
17,51,Renata.llanten@estudiantes.colegiotgs.cl,230444617,2024-09-11 19:19:10
18,52,Tomas.marchant@estudiantes.colegiotgs.cl,227412658,2024-09-11 19:19:10
19,53,Leticia.martinez@estudiantes.colegiotgs.cl,227615591,2024-09-11 19:19:10
20,54,Josefa.morales@estudiantes.colegiotgs.cl,227716975,2024-09-11 19:19:10
21,55,Alejandro.morales@estudiantes.colegiotgs.cl,229785656,2024-09-11 19:19:10
22,56,Matias.morales@estudiantes.colegiotgs.cl,226225609,2024-09-11 19:19:10
23,57,Karla.moya@estudiantes.colegiotgs.cl,229814648,2024-09-11 19:19:10
24,58,Emilia.munoz@estudiantes.colegiotgs.cl,229799614,2024-09-11 19:19:10
25,59,Isidora.navarro@estudiantes.colegiotgs.cl,229996118,2024-09-11 19:19:10
26,60,Monserratt.nincolaf@estudiantes.colegiotgs.cl,228895539,2024-09-11 19:19:10
27,61,Matilde.ojeda@estudiantes.colegiotgs.cl,228365831,2024-09-11 19:19:10
28,62,Maria.olguin@estudiantes.colegiotgs.cl,22765497K,2024-09-11 19:19:10
29,63,Franco.oliva@estudiantes.colegiotgs.cl,230407029,2024-09-11 19:19:10
30,64,Martin.olivares@estudiantes.colegiotgs.cl,229607251,2024-09-11 19:19:10
31,65,Matias.ortiz@estudiantes.colegiotgs.cl,228630845,2024-09-11 19:19:10
32,66,Florencia.perez@estudiantes.colegiotgs.cl,227954299,2024-09-11 19:19:10
33,67,Diego.pino@estudiantes.colegiotgs.cl,229180649,2024-09-11 19:19:10
34,68,Juan.riquelme@estudiantes.colegiotgs.cl,227044810,2024-09-11 19:19:10
35,69,Romero.antonia@estudiantes.colegiotgs.cl,229149059,2024-09-11 19:19:10
36,70,Josefa.toledo@estudiantes.colegiotgs.cl,230515492,2024-09-11 19:19:10
37,71,Matias.venegas@estudiantes.colegiotgs.cl,229135740,2024-09-11 19:19:10
38,72,Daniel.vera@estudiantes.colegiotgs.cl,229338951,2024-09-11 19:19:10
39,73,Martin.vilches@estudiantes.colegiotgs.cl,229952331,2024-09-11 19:19:10
40,74,paz.guzman@estudiantes.colegiotgs.cl,228908061,2024-09-11 19:19:10

## Verificar si el email ya existe en la base de datos

In [10]:
def verify_email(email):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM emails WHERE email = ?", (email,))
    result = cursor.fetchone()
    if result:
        conn.close()
        return True

    else:
        conn.close()
        return False

## Insertar un registro de una inscripción de electivos en la base de datos

In [11]:
def insert_user_record(name, run, email, curso, electivo_1, electivo_2, electivo_3, electivo_fg):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()

    try:
        cursor.execute(
            "INSERT INTO users_register (name, run, email, curso, electivo_1, electivo_2, electivo_3, electivo_fg) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (name, run, email, curso, electivo_1, electivo_2, electivo_3, electivo_fg),
        )
        conn.commit()  # Guarda los cambios
        print("Registro insertado correctamente.")
        return True  # Devuelve True si la inserción fue exitosa
    except Exception as e:
        print(f"Error al insertar el registro: {e}")
        return False  # Devuelve False si hubo un error
    finally:
        conn.close()  # Asegúrate de cerrar la conexión

In [12]:
def verify_email(email):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM emails WHERE email = ?", (email,))
    result = cursor.fetchone()
    if result:
        conn.close()
        return True

    else:
        conn.close()
        return False

In [13]:
def insert_electives(nombre_electivo):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO electives_control (electivos_disponibles) VALUES (?)",
        (nombre_electivo,),
    )
    conn.commit()
    conn.close()
    return True

In [14]:
def drop_columns(table_name, columns):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()
    for column in columns:
        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {column}")
    conn.commit()
    conn.close()
    return True

In [15]:
import pandas as pd
path = "Control_Electivos.csv"

df_electivos = pd.read_csv(path)
df_electivos.head(20)

,Electivos Disponibles,Cantidad de Inscritos,Cupo Disponible,Cupo Asignado
0,Área A: Comprensión Histórica del Presente,0,25,25
1,"Área B: Límites, Derivadas e Integrales",0,25,25
2,Área C: Interpretación Musical,0,25,25
3,Área A: Taller de literatura,0,25,25
4,Área B: Biología celular y molecular.,0,25,25
5,Área B: Pensamiento computacional y programación.,0,25,25
6,"Área C: Artes visuales, audiovisuales y multim...",0,25,25
7,Área A: Lectura y escritura especializada,0,25,25
8,Área B: Química,0,25,25
9,Área C: Ciencias del ejercicio físico y deportivo,0,25,25
10,"Historia, Geografía y Cs. Sociales",0,25,25
11,Arte Visuales,0,25,25

In [16]:
for elective in df_electivos["Electivos Disponibles"]:
    insert_electives(elective)

In [17]:
read_table("electives_control", "form_app.db")

    id                              electivos_disponibles
0    1         Área A: Comprensión Histórica del Presente
1    2            Área B: Límites, Derivadas e Integrales
2    3                     Área C: Interpretación Musical
3    4                       Área A: Taller de literatura
4    5              Área B: Biología celular y molecular.
5    6  Área B: Pensamiento computacional y programación.
6    7  Área C: Artes visuales, audiovisuales y multim...
7    8          Área A: Lectura y escritura especializada
8    9                                    Área B: Química
9   10  Área C: Ciencias del ejercicio físico y deportivo
10  11                 Historia, Geografía y Cs. Sociales
11  12                                      Arte Visuales
12  13         Área A: Comprensión Histórica del Presente
13  14            Área B: Límites, Derivadas e Integrales
14  15                     Área C: Interpretación Musical
15  16                       Área A: Taller de literatura
16  17              Área B: Biología celular y molecular.
17  18  Área B: Pensamiento computacional y programación.
18  19  Área C: Artes visuales, audiovisuales y multim...
19  20          Área A: Lectura y escritura especializada
20  21                                    Área B: Química
21  22  Área C: Ciencias del ejercicio físico y deportivo
22  23                 Historia, Geografía y Cs. Sociales
23  24                                      Arte Visuales

## Contar la cantidad de inscripciones por electivo

In [18]:
def validate_elective_availability(
    electivo_elegido: str, electivo: str, availavity: int
):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()

    try:
        cursor.execute(
            f"SELECT COUNT({electivo}) FROM users_register WHERE {electivo} = ?",
            (electivo_elegido,),
        )
        result = cursor.fetchone()
        if result[0] >= availavity:
            return False
        else:
            return result[0], True
    except Exception as e:
        raise e
    finally:
        conn.close()

In [86]:
validate_elective_availability("Área B: Pensamiento computacional y programación", "electivo_2", 5)

False

In [19]:
def validate_elective_availability_fg(electivo_fg: str, curso: str, availavity: int, ):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()

    try:
        cursor.execute(
            f"SELECT COUNT(electivo_fg) FROM users_register WHERE electivo_fg = ? AND curso = ?",
            (electivo_fg, curso),
        )
        result = cursor.fetchone()
        if result[0] >= availavity:
            return True
        else:
            return False
    except Exception as e:
        raise e
    finally:
        conn.close()

In [60]:
validate_elective_availability_fg("Historia, Geografía y Cs. Sociales", "III BLUE", 10)

0

In [20]:
def validate_run_email(run: str, email: str, table_name="users_register"):
    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()

    try:
        cursor.execute(
            f"SELECT run, email FROM {table_name} WHERE run = ? AND email = ?",
            (run, email),
        )
        result = cursor.fetchone()
        return True if result else False

    except Exception as e:
        raise e
    finally:
        conn.close()

In [128]:
validate_run_email('12256365-8', 'ilaqueso17@gmail.com', 'emails')

False

In [21]:
def insert_data_electivos_2024_3_medio(run, curso, electivo_1, electivo_2, electivo_3):
    conn = sqlite3.connect('form_app.db')
    cursor = conn.cursor()
    cursor.execute(
        """
        INSERT INTO listado_electivos_2024_3_medio (run, curso, electivo_1, electivo_2, electivo_3)
        VALUES (?, ?, ?, ?, ?)
        """,
        (run, curso, electivo_1, electivo_2, electivo_3),
    )
    conn.commit()
    conn.close()

In [22]:
df_electivos_2024_3_medio = pd.read_csv("./listado_electivos_2024_3_medio.csv")

In [27]:
cols = list(df_electivos_2024_3_medio.columns)

In [33]:
for index, row in df_electivos_2024_3_medio.iterrows():
    r = row[cols[0]]
    c = row[cols[1]]
    e1 = row[cols[2]]
    e2 = row[cols[3]]
    e3 = row[cols[4]]
    insert_data_electivos_2024_3_medio(r, c, e1, e2, e3)

In [63]:
def verify_electivo_prior_year(run: str, electivo: str):

    run = run.replace("-", "")

    conn = sqlite3.connect("form_app.db")
    cursor = conn.cursor()

    try:
        cursor.execute(
            f"SELECT run, electivo_1, electivo_2, electivo_3 FROM listado_electivos_2024_3_medio WHERE run = ?",
            (run,),
        )
        result = cursor.fetchone()
        if result:
            if electivo in list(result[1:]):
                return True
            else:
                return False
    except Exception as e:
        raise e
    finally:
        conn.close()

In [66]:
verify_electivo_prior_year("22464776-K", "Economía y Sociedad")

True

In [ ]:
'Interpretación Musical'

In [37]:
table_name = "listado_electivos_2024_3_medio"
db = "form_app.db"

read_table(table_name, db)

,id,run,curso,electivo_1,electivo_2,electivo_3
0,1,224332564,3º Medio B,Física,Ciencias del Ejercicio Físico y Deportivo,Interpretación Musical
1,2,22464776K,3º Medio A,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
2,3,224793626,3º Medio B,Diseño y arquitectura,Biología celular y molecular,Interpretación Musical
3,4,224793839,3º Medio B,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
4,5,225014434,3º Medio A,Participación y Argumentación,Economía y Sociedad,Interpretación Musical
...,...,...,...,...,...,...
69,70,226483306,3º Medio B,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
70,71,226600493,3º Medio A,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
71,72,226821848,3º Medio B,Diseño y arquitectura,Biología celular y molecular,Seminario de filosofía
72,73,227016558,3º Medio B,Participación y Argumentación,Ciencias de la salud,Seminario de filosofía
73,74,227150645,3º Medio B,Física,Ciencias del Ejercicio Físico y Deportivo,Seminario de filosofía